### ISSUE TITLE
Error 500 Undefined variable: result

### ISSUE THREAD

**Issue by Plofkat** [marcelofmatos/phpnetmap#5]
I'm getting a lot of these errors running on server without docker.
Any idea what I'm doing wrong?

`REQUEST_URI=/phpnetmap/search/index
2020/06/25 15:28:40 [error] [php] Undefined variable: result (/var/www/phpnetmap/protected/views/search/index.php:14)
Stack trace:
#0 /var/www/phpnetmap/yii/framework/web/CController.php(869): SearchController->renderFile()
#1 /var/www/phpnetmap/yii/framework/web/CController.php(782): SearchController->renderPartial()
#2 /var/www/phpnetmap/protected/controllers/SearchController.php(42): SearchController->render()
#3 /var/www/phpnetmap/yii/framework/web/actions/CInlineAction.php(49): SearchController->actionIndex()
#4 /var/www/phpnetmap/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/phpnetmap/yii/framework/web/CController.php(286): SearchController->runAction()
#6 /var/www/phpnetmap/yii/framework/web/CController.php(265): SearchController->runActionWithFilters()
#7 /var/www/phpnetmap/yii/framework/web/CWebApplication.php(282): SearchController->run()
#8 /var/www/phpnetmap/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/phpnetmap/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10 /var/www/phpnetmap/index.php(13): CWebApplication->run()
REQUEST_URI=/phpnetmap/search/index
`

**Comment by marcelofmatos** [comment]
Corrigido em db1cf2a (fechada automaticamente pelo push, via "Fixes #5" na mensagem do commit).

Causa: `SearchController::actionIndex()` e `actionResult()` só passavam a variável `result` pra view quando o formulário era submetido e validado com sucesso. No primeiro carregamento da página (GET simples, sem submit) ou quando a validação falhava, `result` nunca era passado pra `search/index.php`, e a linha 14 (`if ($result)`) disparava o "Undefined variable: result" — em servidores sem a supressão de notices que a imagem Docker do projeto aplica, isso aparece nos logs como no relato acima.

`actionResult()` também não passava `searchModel`, o que quebraria `switch ($searchModel->type)` mais abaixo na mesma view quando havia resultado.
